### ISSUE TITLE
validate-value Parser throws when passing in a circular schema configuration

### ISSUE THREAD

**Issue by matthiashermsen** [thenativeweb/validate-value#431]
I want to validate a custom filter object which might contain logical operators. If that's the case, there will be multiple nested filters again.

I configured the schema for it but the [constructor of `Parser`](https://github.com/thenativeweb/validate-value/blob/main/lib/Parser.ts#L21) throws something like

```
RangeError: Maximum call stack size exceeded
    at andSchema (/home/.../app.ts:17:38)
    at filterSchema (/home/.../app.ts:14:12)
    at andSchema (/home/.../app.ts:22:14)
    at filterSchema (/home/.../app.ts:14:12)
    at andSchema (/home/.../app.ts:22:14)
    at filterSchema (/home/.../app.ts:14:12)
    at andSchema (/home/.../app.ts:22:14)
    at filterSchema (/home/.../app.ts:14:12)
    at andSchema (/home/.../app.ts:22:14)
    at filterSchema (/home/.../app.ts:14:12)
```

Although the code is very similiar to _ajv_ it makes use of `JSONSchema7` instead of `Schema`. Unfortunately I wasn't able to find out how to fix this but I tried to reproduce it. The following is a fork with custom modifications, I run the tests with `npm run test` and you can find the relevant part inside the [test directory on the reproduction branch](https://github.com/matthiashermsen/validate-value/tree/reproduction/test).

Just to make things clear, I added `JsonSchema` configurations for validate-value and `Schema` configurations for ajv, those are prefixed with *ajv* :)

Please let me know if you need more information

**Comment by yeldiRium** [comment]
The problem here seems to be that in one implementation you use functions to create the schema objects and in the other implementation you define the objects directly.

The function-based implementation will run into the max call stack issue, since it is an infinite recursion of function calls. There is no way around that.
The object-based implementation does not have this problem, since the objects are each defined only once and then reference each other. Although I don't entirely understand why this works, since it still contains circular imports, but JavaScript might be smart enough for that.

So what you can do is use the `validate-value` `Parser` constructor with the object-based implementation of your schema and everything should be fine:

```typescript
  test('does not throw with a circular schema.', async (): Promise<void> => {
    assert.that((): void => {
      new Parser(ajvFilterSchema);
    }).is.not.throwing();
  });
```

Also you can replace the ajv `Schema` type with the internal `JsonSchema` type in your test files (`andSchema.ts` and `filterSchema.ts`). It works as well.

This is not a bug.
